name: CashblockMiners
version: 1.0
main: pl.sexozix.cashblockminers.CashBlockPlugin
api-version: 1.16
commands:
  money:
    aliases: [hajs, pieniadze]
    description: Pokazuje ile masz hajsu na koncie
    usage: /money
  wygrana:
    aliases: [win]
    usage: /wygrana
  przegrana:
    aliases: [lose]
  podlozpitos:
    aliases: [podlozhajs, blockmoney]
  tops:
    aliases: [topki]
  boost:
    aliases: [playerboost, turbocash]

